version: '3.7'
services:
  portainer:
    container_name: portainer_container
    image: portainer/portainer-ce
    command: --admin-password '$$2y$$05$$aBO2g/CyILjPqUslk.77jOIJLooKq8v/lu.BrP4WAjJHNIlEzDqZm'
    #environment: 
    # - EXAMPLE=value
    ports:
      - "${ptport:-9000}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
      #- /var/lib/docker/portainer:/tmp/portainer

volumes:
  data:

networks:
  default:
    external: true
    name: "${net}"
