version: "3.9"
  
services:
  jenkins:
    image: "orboan/jenkins:lts-jdk11"
    container_name: jenkins_container
    privileged: true
    environment:
      JAVA_OPTIONS: "-Xmx1024m -Xms256m"
      JENKINS_OPTS: "--prefix=/user/${NB_USER}/jenkins"
    volumes:
      - "home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${jenkinsport:-8011}:8080"
      - "50000:50000"

volumes:
    home:

networks:
  default:
    external: true
    name: "${net:-entornet}"





