version: '3.5'
  
services:
  sonarqube:
    container_name: sonarqube_container
    image: sonarqube:lts
    command: "-Dsonar.web.context=/user/${NB_USER}/sonarqube"
    depends_on:
      - postgres
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - ~/.config/sonar.properties:/opt/sonarqube/conf/sonar.properties
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9090:9090"

  postgres:
    container_name: sonar_postgres_container
    image: postgres:11.14
    environment:
      POSTGRES_USER: ${NB_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pluralcamp}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - data:/data/postgres
      - /var/run/postgresql:/var/run/postgresql
    ports:
      - "5431:5432"    

  pgadmin:
    container_name: sonar_pgadmin_container
    #image: dpage/pgadmin4:latest
    build: .
    environment:
      PGADMIN_DEFAULT_EMAIL: "${NB_USER}@ilg.cat"
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-pluralcamp}
      PGADMIN_DISABLE_POSTFIX: 'True'
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_LISTEN_PORT: '80'
      PGADMIN_PORT: "5060"
      PGADMIN_CONFIG_X_FRAME_OPTIONS: '""'
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: '2'
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: '2'
      PGADMIN_CONFIG_X_CONTENT_TYPE_OPTIONS: '""'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_config:/pgadmin4
    ports:
      - "5060:80"

networks:
  default:
    external: true
    name: "${net:-entornet}"

volumes:
    data:
    pgadmin_data:
    pgadmin_config:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:      

